name: Build and Deploy Jupyter Book

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-book:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt

    - name: Install Jupyter Book and Psydac
      run: pip3 install -r requirements.txt

    - name: Build Jupyter Book
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      run: ghp-import -n -p -f _build/html
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}